[book]
title = "Il Linguaggio di Programmazione Rust"
authors = ["Steve Klabnik", "Carol Nichols", "Contribuzioni dalla comunità di Rust", "Traduzione del Rust User Group di Verona"]

[output.html]
additional-css = ["ferris.css", "theme/2018-edition.css"]
additional-js = ["ferris.js"]
git-repository-url = "https://github.com/Rust-User-Group-VR/rust_book_ita"
