# We use the GPT-4 model in order to be able to reliably use the ignorelist below
gptmodel = "gpt-4o"

# The default prompt with an additional clause to avoid getting the source code (or examples' output) translated
sysprompt = "You shall translate the following markdown to Italian, preserving the existing formatting and avoiding any other output. Please refrain from translating anything inside a Markdown Code Block."

# List of domain-specific terms that GPT shouldn't translate
ignorelist = [
  "Ownership",
  "Owner",
  "Owners",
  "Borrowing",
  "Borrow",
  "Lifetime",
  "Trait",
  "Traits",
  "Struct",
  "Structs",
  "Enum",
  "Match",
  "Option",
  "Result",
  "Crate",
  "Crates",
  "Module",
  "Cargo",
  "Slice",
  "Slices",
  "Iterator",
  "Closure",
  "Closures",
  "Mutable",
  "Mutables",
  "Immutable",
  "Immutables",
  "Reference",
  "References",
  "Borrow Checker",
  "Concurrency",
  "Mutex",
  "Atomic",
  "Async",
  "Smart Pointer",
  "Unsafe",
  "Closure",
  "Closures",
  "Appendix",
  "Appendicies",
  "Reference-like",
  "Hello, world",
  "Rustacean",
  "Rustaceans",
  "Scope",
  "Failed",
  "Guess",
  "Unsigned",
  "Signed",
  "Loop",
  "Loops",
  "Looping",
  "Shadowing",
  "Shadowed",
  "Shadow",
  "Panic",
  "Wrapping",
  "Wrapped",
  "Wrap",
  "Arm",
  "Arms",
  "Host",
  "Swallow Copy",
  "Deep Copy",
  "Data Race",
  "Range",
  "String",
  "Clean",
  "Listing",
  "List",
  "Glob Operator",
  "Pattern",
  "Patterns",
  "Package",
  "Packages",
  "Path",
  "Paths"
]


# PLEASE NOTE: The OpenAI API key isn't saved here for obvious reasons and you should
#              never commit this file in case you edit it into.
#              To pass the API key to the program please run it with the following
#              syntax: "GPTMDT_OPENAITOKEN=... gpt_md_translator ..."
