name: "Rust Book ITA Build"
on:
  pull_request:
  push:
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Git repo
        uses: actions/checkout@v4
      - name: Setup Nix
        uses: nixbuild/nix-quick-install-action@v26
      - name: Restore and cache Nix store
        uses: nix-community/cache-nix-action@v4
        with:
          key: cache-${{ matrix.os }}-${{ hashFiles('**/*.nix') }}-${{ hashFiles('**/*.lock', '**/Cargo.toml') }}
          restore-keys: |
            cache-${{ matrix.os }}-${{ hashFiles('**/*.nix') }}
            cache-${{ matrix.os }}
      - name: Build the Book
        run: nix build
      - name: Get the Book Artifacts
        run: mkdir -p rust_book_ita && cp -r result/* rust_book_ita/
      - name: Upload the Book Artifacts
        uses: actions/upload-artifact@v3
        continue-on-error: true
        with:
          name: rust_book_ita
          path: rust_book_ita/
          retention-days: 30